### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [MLH-Fellowship/alphadoc#16]
I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by V2dha** [comment]
Thanks for your inputs. I have added the required labels.

**Comment by akrish4** [comment]
#19   PR

**Comment by V2dha** [comment]
Hey @akrish4 I am sorry but this pr is labelled incorrectly as its of level 2. So I'll assign a level 2 tag to this.

**Comment by akrish4** [comment]
> Hey @akrish4 I am sorry but this pr is labelled incorrectly as its of level 2. So I'll assign a level 2 tag to this.

okay thank you 
i have added the file now you just have to install and configure the bot using the official website of github app https://github.com/apps/welcome , and bot will do it on its own
