### ISSUE TITLE
Automatically update the contributors in readme

### ISSUE THREAD

**Issue by V2dha** [MLH-Fellowship/alphadoc#23]
Is there a way to automatically update the contributors in the readme with emoji associated with the type of contribution for instance by looking at the label like documentation or enhancement.

**Comment by Dhriti-Roy** [comment]
I want to start working on it. Kindly assign this to me.

**Comment by V2dha** [comment]
Thanks @Dhriti-Roy. Can you tell me how you are planning to do that?

**Comment by tusharnankani** [comment]
Hi @V2dha 

I would like to work on this.

There are 2 approaches.

1. Statically generated.

![image](https://user-images.githubusercontent.com/61280281/105512389-0d9cf600-5cf7-11eb-8598-5c9f193f308c.png)

- These will be static and won't link the individual contributor.
2. Dynamically generated
- These are generated dynamically and look like this.

![image](https://user-images.githubusercontent.com/61280281/105512497-2dccb500-5cf7-11eb-86f0-bcc712b65118.png)

This process is quite cumbersome as you have to call the bot every time you get a PR merged. Here, you have to call specifically call the @/all-contributors bot and ask it to update the README once a PR is merged. 

`@all-contributors please add @V2dha for code`
or
`@all-contributors please add @V2dha for docs, review`

And the bot will create a PR. 


Let me know which one should I go ahead with?

**Comment by V2dha** [comment]
@tusharnankani Thank you for the detailed explanation! I think the dynamic one would be good with @all-contributors bot. The contributors themselves can call the bot to update the README once their PR gets merged.

**Comment by tusharnankani** [comment]
> The contributors themselves can call the bot to update the README once their PR gets merged.

@V2dha 
The owner/maintainer of the repository can comment on it.

**Comment by V2dha** [comment]
> > The contributors themselves can call the bot to update the README once their PR gets merged.
> 
> @V2dha
> The owner/maintainer of the repository has to comment on it.

Then I can think static one is fine for now. Will consider the bot one some other time.

**Comment by tusharnankani** [comment]
> Then I can think static one is fine for now. Will consider the bot one some other time.

Alright! Going ahead with the first one.

**Comment by tusharnankani** [comment]
@V2dha does this come under any level in DWOC?

**Comment by V2dha** [comment]
> @V2dha does this come under any level in DWOC?

Yes it does. I'll add the suitable level with dwoc tag.
